repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.5
    hooks:
      - id: ruff
        args: ["--fix"]
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
  - repo: local
    hooks:
      - id: manifest-verify
        name: manifest-verify
        entry: python -m echo.cli manifest verify
        language: system
        pass_filenames: false
