repos:
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks: [ { id: black } ]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.5
    hooks: [ { id: ruff, args: [--fix] } ]
  - repo: local
    hooks:
      - id: echo-manifest-verify
        name: echo-manifest-verify
        entry: python -m echo.cli manifest-verify
        language: system
        pass_filenames: false
