repos:
  - repo: local
    hooks:
      - id: echo-amplify-manifest
        name: Echo Amplify Manifest Sync
        entry: python -m echo.manifest_cli amplify now --update-manifest
        language: system
        pass_filenames: false
