# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import identity_pb2 as identity__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in identity_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IdentityLayerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListKeys = channel.unary_unary(
                '/echo.identity.IdentityLayer/ListKeys',
                request_serializer=identity__pb2.Empty.SerializeToString,
                response_deserializer=identity__pb2.KeyList.FromString,
                _registered_method=True)
        self.EnsureKey = channel.unary_unary(
                '/echo.identity.IdentityLayer/EnsureKey',
                request_serializer=identity__pb2.KeyRequest.SerializeToString,
                response_deserializer=identity__pb2.KeyRecord.FromString,
                _registered_method=True)
        self.Rotate = channel.unary_unary(
                '/echo.identity.IdentityLayer/Rotate',
                request_serializer=identity__pb2.KeyRequest.SerializeToString,
                response_deserializer=identity__pb2.KeyRecord.FromString,
                _registered_method=True)
        self.Sign = channel.unary_unary(
                '/echo.identity.IdentityLayer/Sign',
                request_serializer=identity__pb2.SignRequest.SerializeToString,
                response_deserializer=identity__pb2.SignResponse.FromString,
                _registered_method=True)
        self.History = channel.unary_unary(
                '/echo.identity.IdentityLayer/History',
                request_serializer=identity__pb2.Empty.SerializeToString,
                response_deserializer=identity__pb2.HistoryResponse.FromString,
                _registered_method=True)


class IdentityLayerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListKeys(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnsureKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Rotate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Sign(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def History(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IdentityLayerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListKeys': grpc.unary_unary_rpc_method_handler(
                    servicer.ListKeys,
                    request_deserializer=identity__pb2.Empty.FromString,
                    response_serializer=identity__pb2.KeyList.SerializeToString,
            ),
            'EnsureKey': grpc.unary_unary_rpc_method_handler(
                    servicer.EnsureKey,
                    request_deserializer=identity__pb2.KeyRequest.FromString,
                    response_serializer=identity__pb2.KeyRecord.SerializeToString,
            ),
            'Rotate': grpc.unary_unary_rpc_method_handler(
                    servicer.Rotate,
                    request_deserializer=identity__pb2.KeyRequest.FromString,
                    response_serializer=identity__pb2.KeyRecord.SerializeToString,
            ),
            'Sign': grpc.unary_unary_rpc_method_handler(
                    servicer.Sign,
                    request_deserializer=identity__pb2.SignRequest.FromString,
                    response_serializer=identity__pb2.SignResponse.SerializeToString,
            ),
            'History': grpc.unary_unary_rpc_method_handler(
                    servicer.History,
                    request_deserializer=identity__pb2.Empty.FromString,
                    response_serializer=identity__pb2.HistoryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'echo.identity.IdentityLayer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('echo.identity.IdentityLayer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IdentityLayer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListKeys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/echo.identity.IdentityLayer/ListKeys',
            identity__pb2.Empty.SerializeToString,
            identity__pb2.KeyList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnsureKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/echo.identity.IdentityLayer/EnsureKey',
            identity__pb2.KeyRequest.SerializeToString,
            identity__pb2.KeyRecord.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Rotate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/echo.identity.IdentityLayer/Rotate',
            identity__pb2.KeyRequest.SerializeToString,
            identity__pb2.KeyRecord.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Sign(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/echo.identity.IdentityLayer/Sign',
            identity__pb2.SignRequest.SerializeToString,
            identity__pb2.SignResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def History(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/echo.identity.IdentityLayer/History',
            identity__pb2.Empty.SerializeToString,
            identity__pb2.HistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
