name: Bug
description: Something broke or is incorrect
labels: ["bug"]
body:
  - type: input
    id: version
    attributes:
      label: Version/Tag
      placeholder: "v0.1.0"
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: "1)… 2)… 3)…"
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected vs Actual
