// Auto-generated by scripts/generate_clients.py

export interface ChatRequest {
  message: string;
  inputs?: Record<string, unknown>;
  execute?: boolean;
}

export interface ChatResponse {
  function: string;
  message: string;
  data: Record<string, unknown>;
  metadata: Record<string, unknown>;
}

export interface FunctionDescription {
  name: string;
  description: string;
  parameters: Record<string, unknown>;
  metadata: Record<string, unknown>;
}

export interface FunctionListResponse {
  functions: FunctionDescription[];
}

export class EchoComputerAgentClient {
  private readonly baseUrl: string;
  private readonly defaultHeaders: Record<string, string>;

  constructor(baseUrl: string, defaultHeaders: Record<string, string> = {}) {
    this.baseUrl = baseUrl.replace(/\/+$|\s+$/g, '').replace(/\/+$/, '');
    this.defaultHeaders = { ...defaultHeaders };
  }

  async listFunctions(signal?: AbortSignal): Promise<FunctionListResponse> {
    const response = await fetch(`${this.baseUrl}/functions`, {
      method: 'GET',
      headers: { ...this.defaultHeaders },
      signal,
    });
    if (!response.ok) {
      throw new Error(`Request failed with status ${response.status}`);
    }
    return (await response.json()) as FunctionListResponse;
  }

  async chat(request: ChatRequest, signal?: AbortSignal): Promise<ChatResponse> {
    const response = await fetch(`${this.baseUrl}/chat`, {
      method: 'POST',
      headers: { 'content-type': 'application/json', ...this.defaultHeaders },
      body: JSON.stringify(request),
      signal,
    });
    if (!response.ok) {
      throw new Error(`Request failed with status ${response.status}`);
    }
    return (await response.json()) as ChatResponse;
  }
}
