site_name: EchoCore
nav:
  - Home: index.md
  - Echo:
      - Overview: echo/overview.md
      - Attestations: echo/attestations.md
      - Amplification: echo/amplification.md
theme:
  name: material
