name: attestation-broadcast

on:
  push:
    branches:
      - main
    paths:
      - federated_attestation_index.json
      - federated_attestation_feed.xml
      - verification.log

jobs:
  broadcast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Publish attestation signal
        run: |
          python3 scripts/post_attestation_social.py \
            --index federated_attestation_index.json \
            --base-url "${{ github.server_url }}/${{ github.repository }}"
        env:
          MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
          MASTODON_BASE_URL: ${{ secrets.MASTODON_BASE_URL }}
