name: Colossus CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: python -m compileall colossus

  schemas:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python -m json.tool schemas/artifact.schema.json
