name: Echo Omni-Fusion

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: make constellation
      - run: python scripts/oracle.py
      - run: python scripts/verify_proof.py
      - run: python scripts/domain_bridge.py
      - run: python scripts/swarm.py
      - name: Self-healing attempt
        if: failure()
        run: |
          echo "Attempting automated recovery" >&2
          python scripts/oracle.py --repair-only || true
          python scripts/swarm.py --nodes 3 --rounds 2 --quorum 1 || true
          echo "Recovery artifacts stored in build/ for follow-up review" >&2
