name: Echo Manifest Gate

on:
  push:
    branches:
      - main
      - '**'
  pull_request:

jobs:
  manifest:
    name: Validate Echo Manifest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Validate manifest
        run: |
          python tools/echo_manifest.py validate
