name: Echo Amplify Gate

on:
  pull_request:
    branches: ["*"]

jobs:
  amplify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Run unit tests
        run: pytest -q
      - name: Enforce amplification gate
        env:
          AMPLIFY_MIN: ${{ secrets.AMPLIFY_MIN }}
        run: |
          MINIMUM=${AMPLIFY_MIN:-70}
          python -m echo --log-path state/amplify_log.jsonl --manifest-path echo_manifest.json amplify gate --min "$MINIMUM"
