name: Echo Manifest

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate:
    name: Validate manifest
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -e .[dev]

      - name: Validate echo manifest
        run: python tools/echo_manifest.py validate
