name: Manifest Check

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install project
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .

      - name: Refresh manifest
        run: echo manifest refresh

      - name: Ensure manifest is up to date
        run: git diff --exit-code echo_manifest.json

      - name: Verify manifest
        run: echo manifest verify
