name: Manifest Check

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  manifest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install project
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Refresh manifest
        run: |
          echo manifest refresh
      - name: Verify manifest
        run: |
          echo manifest verify
